### ISSUE TITLE
Flutter 2.0 & Null Safety support?

### ISSUE THREAD

**Issue by nipunasudha** [Workiva/w_common#139]

**Comment by zmeggyesi** [comment]
@georgelesica-wf SASS-compilation is problematic in this migration, as it depends on a deprecated package (`package_resolver`) and it has conflicts which practically make dependency resolution impossible. Same goes for `dependency_validator`, it looks like.

While I did manage to upgrade the package dependencies to support Flutter 2, it came at the cost of SASS-compilation and dep validation - how big a problem that is, I'm not sure yet.

**Comment by travissanderson-wf** [comment]
Hey guys, these packages are still maintained and we are also interested in getting to NNBD!  I did a little digging and found that package_resolver is used as part of the public API for sass.  The Dart team is actively working on making sass NNBD which will involve eliminating that as a dep - see Nex's branch https://github.com/sass/dart-sass/compare/nnbd.  We also have some dev deps that depend on updates from the Dart team around the build_runner/build_test stuff, but it is possible we could figure out a workaround for those.  I haven't investigated dependency_validator yet.

**Comment by travissanderson-wf** [comment]
FYI we merged https://github.com/Workiva/w_common/pull/141 which allows using w_common in Dart 2.12 (but does not support null safety)

**Comment by nipunasudha** [comment]
Thank you very much. Is there any way you can make `state_machine` package independent from the `Disposable` utilities? May be by allowing users to manually call a Machine.dispose() method?

**Comment by travissanderson-wf** [comment]
let's have that discussion on that repo :)

**Comment by zmeggyesi** [comment]
Well now, things are moving... good to see that 👀

**Comment by evanweible-wf** [comment]
We also depend on the `colorize` package which has merged a null-safe version but has not yet published it - hopefully that should happen soon. But if that ends up being our last blocker, we could use `package:io` instead.

We should be able to migrate without waiting for `build_runner` or `build_web_compilers` since we don't import them, just use them to run builders.

And I put up a PR to migrate `dependency_validator` here: https://github.com/Workiva/dependency_validator/pull/71

**Comment by timothysteward-wk** [comment]
`w_common` now supports `null` safety.
